export const paises = [
    { nombre: "Alemania", codigo: "de" },
    { nombre: "Ghana", codigo: "gh" },
    { nombre: "Grecia", codigo: "gr" },
    { nombre: "Guatemala", codigo: "gt" },
    { nombre: "Guinea", codigo: "gn" },
    { nombre: "Haití", codigo: "ht" },
    { nombre: "Honduras", codigo: "hn" },
    { nombre: "Hong Kong", codigo: "hk" },
    { nombre: "Hungría", codigo: "hu" },
    { nombre: "Islandia", codigo: "is" },
    { nombre: "India", codigo: "in" },
    { nombre: "Indonesia", codigo: "id" },
    { nombre: "Irak", codigo: "iq" },
    { nombre: "Irlanda", codigo: "ie" },
    { nombre: "Israel", codigo: "il" },
    { nombre: "Italia", codigo: "it" },
    { nombre: "Jamaica", codigo: "jm" },
    { nombre: "Japón", codigo: "jp" },
    { nombre: "Jordán", codigo: "jo" },
    { nombre: "Kazajstán", codigo: "kz" },
    { nombre: "Kenia", codigo: "ke" },
    { nombre: "Kuwait", codigo: "kw" },
    { nombre: "Kirguistán", codigo: "kg" },
    { nombre: "letonia", codigo: "lv" },
    { nombre: "Líbano", codigo: "lb" },
    { nombre: "Libia", codigo: "ly" },
    { nombre: "Lituania", codigo: "lt" },
    { nombre: "luxemburgo", codigo: "lu" },
    { nombre: "Macao", codigo: "mo" },
    { nombre: "macedonia", codigo: "mk" },
    { nombre: "Madagascar", codigo: "mg" },
    { nombre: "Malaui", codigo: "mw" },
    { nombre: "Malasia", codigo: "my" },
    { nombre: "Maldivas", codigo: "mv" },
    { nombre: "Malí", codigo: "ml" },
    { nombre: "Malta", codigo: "mt" },
    { nombre: "Mauritania", codigo: "mr" },
    { nombre: "México", codigo: "mx" },
    { nombre: "Moldavia", codigo: "md" },
    { nombre: "Mongolia", codigo: "mn" },
    { nombre: "montenegro", codigo: "me" },
    { nombre: "Marruecos", codigo: "ma" },
    { nombre: "Mozambique", codigo: "mz" },
    { nombre: "Birmania", codigo: "mm" },
    { nombre: "Namibia", codigo: "na" },
    { nombre: "Nepal", codigo: "np" },
    { nombre: "Holanda", codigo: "nl" },
    { nombre: "Nueva Zelanda", codigo: "nz" },
    { nombre: "Níger", codigo: "ne" },
    { nombre: "Nigeria", codigo: "ng" },
    { nombre: "Corea del Norte", codigo: "kp" },
    { nombre: "Noruega", codigo: "no" },
    { nombre: "Omán", codigo: "om" },
    { nombre: "Pakistán", codigo: "pk" },
    { nombre: "Panamá", codigo: "pa" },
    { nombre: "Paraguay", codigo: "py" },
    { nombre: "Perú", codigo: "pe" },
    { nombre: "Filipinas", codigo: "ph" },
    { nombre: "Polonia", codigo: "pl" },
    { nombre: "Portugal", codigo: "pt" },
    { nombre: "Puerto Rico", codigo: "pr" },
    { nombre: "Rumania", codigo: "ro" },
    { nombre: "Rusia", codigo: "ru" },
    { nombre: "Ruanda", codigo: "rw" },
    { nombre: "samoa", codigo: "ws" },
    { nombre: "San Marino", codigo: "sm" },
    { nombre: "Arabia Saudita", codigo: "sa" },
    { nombre: "Senegal", codigo: "sn" },
    { nombre: "Serbia", codigo: "rs" },
    { nombre: "Singapur", codigo: "sg" },
    { nombre: "Eslovaquia", codigo: "sk" },
    { nombre: "Eslovenia", codigo: "si" },
    { nombre: "Islas Salomón", codigo: "sb" },
    { nombre: "Somalia", codigo: "so" },
    { nombre: "Sudáfrica", codigo: "za" },
    { nombre: "Corea del Sur", codigo: "kr" },
    { nombre: "España", codigo: "es" },
    { nombre: "Sri Lanka", codigo: "lk" },
    { nombre: "Sudán", codigo: "sd" },
    { nombre: "Suecia", codigo: "se" },
    { nombre: "Suiza", codigo: "ch" },
    { nombre: "Siria", codigo: "sy" },
    { nombre: "Taiwán", codigo: "tw" },
    { nombre: "Tayikistán", codigo: "tj" },
    { nombre: "Tanzania", codigo: "tz" },
    { nombre: "Tailandia", codigo: "th" },
    { nombre: "tonga", codigo: "to" },
    { nombre: "Túnez", codigo: "tn" },
    { nombre: "Pavo", codigo: "tr" },
    { nombre: "turkmenistán", codigo: "tm" },
    { nombre: "Uganda", codigo: "ug" },
    { nombre: "Ucrania", codigo: "ua" },
    { nombre: "Emiratos Árabes Unidos", codigo: "ae" },
    { nombre: "Reino Unido", codigo: "gb" },
    { nombre: "Estados Unidos de América", codigo: "us" },
    { nombre: "Uruguay", codigo: "uy" },
    { nombre: "Uzbekistán", codigo: "uz" },
    { nombre: "Venezuela", codigo: "ve" },
    { nombre: "Vietnam", codigo: "vi" },
    { nombre: "Yemen", codigo: "ye" },
    { nombre: "Zambia", codigo: "zm" },
    { nombre: "Zimbabue", codigo: "zw" }
  ];
  
 export  const categorias = [
    "business",
    "entertainment",
    "environment",
    "food",
    "health",
    "politics",
    "science",
    "sports",
    "technology",
    "top",
    "tourism",
    "world"
  ];